version: "3.9"

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: laravel_prod
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: "base64:PM0LoGlOpB8OCxD/WUgRpoj12P7HRi8kpr59SdpgE84="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: stages_db
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod   # ⬅️ NGINX avec ton build dedans
    container_name: nginx_prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/public:/var/www/html/public
    depends_on:
      - laravel
    restart: unless-stopped

  db:
    image: mariadb:11
    container_name: mariadb_prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stages_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data_prod:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data_prod:
