user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        # -------------------------
        # FRONT React
        # -------------------------
        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }

        # -------------------------
        # BACK Laravel (API)
        # TOUT passe par index.php
        # -------------------------
        location /api {
            alias /var/www/html/public;
            try_files $uri /index.php?$query_string;
        }

        # -------------------------
        # PHP → PHP-FPM
        # -------------------------
        location ~ \.php$ {
            root /var/www/html/public;
            fastcgi_pass laravel:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        }
    }
}

