# Étape 1 : Build du frontend React
FROM node:18-alpine AS build

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le reste du code
COPY . .

# Build en production
RUN npm run build


# Étape 2 : NGINX pour servir le build
FROM nginx:alpine

# Copier le build React dans Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Exposer port 80
EXPOSE 80

# Lancer nginx
CMD ["nginx", "-g", "daemon off;"]
