# Étape 1 : Build du frontend React
FROM node:18-alpine AS build

WORKDIR /app

# Réduire la taille du cache npm (important pour les petites VM)
ENV npm_config_cache=/tmp/npm-cache

# Installer les dépendances en mode CI (plus propre et léger que npm install)
COPY package*.json ./
RUN npm ci --prefer-offline --no-audit --no-fund

# Copier le reste du code
COPY . .

# Build en production
RUN npm run build

# Étape 2 : Serveur NGINX pour servir le build
FROM nginx:alpine

# Copier le build React dans Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Exposer port 80
EXPOSE 80

# Lancer nginx
CMD ["nginx", "-g", "daemon off;"]
