# Étape 1 : Build du frontend
FROM node:18-alpine as build

WORKDIR /app

# Installer dépendances
COPY package*.json ./
RUN npm install

# Copier le code et build
COPY . .
RUN npm run build

# Étape 2 : Serveur NGINX pour la production
FROM nginx:alpine

# Copier le build React dans Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Exposer port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
