FROM php:8.2-fpm

# Install deps
RUN apt-get update && apt-get install -y \
    unzip git curl libzip-dev libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql zip gd bcmath

WORKDIR /var/www/html

# Composer
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

# Fix: PHP-FPM doit écouter sur 0.0.0.0
RUN sed -i 's/listen = 127.0.0.1:9000/listen = 9000/' /usr/local/etc/php-fpm.d/www.conf

# Copier code + vendor
COPY . .

RUN composer install --optimize-autoloader --no-dev
RUN php artisan config:cache
RUN php artisan route:cache
RUN php artisan view:cache

RUN chmod -R 777 storage bootstrap/cache
CMD ["php-fpm"]

